
%% plot sanity
Tool_ExamplePlot; title(['Participant #' num2str(whichParticipant,'%03.0f')]); drawnow;
saveas(gcf,[pwd filesep 'temp figures' filesep 'datapresence_' num2str(whichParticipant,'P%03.0f') '.png']);
close(gcf);

%% export csv for each participant
disp('Saving participant session info...');
aFilename = ['P' num2str(whichParticipant,'%03.0f') '-Session'];
writetable(trialInfo,[outPath filesep aFilename '.csv']);

%% make full ppt table
clear tableToExport
tableToExport = table(...
    repmat(whichParticipant,EEG.pnts,1),...
    EEG.trialNumber',...
    EEG.times'/1000,...
    EEG.trialTimes',...
    repmat({''},EEG.pnts,1),...
    'VariableNames',...
    {'participant','trialNumber','sessionTime','trialTime','event'});
tableToExport.event([EEG.event.latency]) = {EEG.event.type}';

% where are offsets? A: lost bc fractional latency value
% Why is onset off by 4ms? A: fractional latencies again

%% join the trial information
% it makes the file really bigger though (650>800MB csv), and adds a LOT of redundant information... disabling for now.
% tableToExport = sortrows(outerjoin(tableToExport,trialInfo,'Keys',{'participant','trialNumber'},'MergeKeys',1,'Type','left'),'sessionTime');

%% add other measures
tableToExport = [tableToExport,...
    array2table(EEG.data(1:64,:)','VariableNames',strcat(repmat({'EEG_'},1,64)',{EEG.chanlocs(1:64).labels}')),...
    array2table(EEG.data(65:66,:)','VariableNames',{'EOG_Vert','EOG_Horz'}),...
    table(...
    EEG.data_ecg',...
    EEG.data_hr',...
    EEG.data_gsr',...
    EEG.data_irp',...
    EEG.data_resp',...
    EEG.data_response',...
    'VariableNames',...
    {'ECG','heartrate','GSR','IRPleth','Respir','contArousal'})];

%% export full csv
disp('Saving participant full data...');
aFilename = ['P' num2str(whichParticipant,'%03.0f') '-Data'];
writetable(tableToExport,[outPath filesep aFilename '.csv']);

%% save EEGLAB set file
EEG.trialInfo = trialInfo;
EEG = pop_saveset(EEG,'filename',num2str(whichParticipant,'P%03.0f'),'filepath',outPath);
